SELECT 'CREATE TABLE Taverns ('
UNION ALL
SELECT CONCAT
('	', COLUMN_NAME, ' ', DATA_TYPE, 
	CASE
		WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN '('
	END
	, CHARACTER_MAXIMUM_LENGTH,
	CASE
		WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN ')'
	END
	, ' ',
	CASE
		WHEN IS_NULLABLE = 'NO' THEN 'NOT NULL'
	END
	, ','
/*	CASE
		WHEN ORDINAL_POSITION != MAX(ORDINAL_POSITION) THEN ','
	END*/
)
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME  = 'Taverns'
UNION ALL
SELECT ');'